package com

import com.routes.arcRoutes
import com.routes.characterRoutes
import com.routes.eraRoutes
import com.routes.eventRoutes
import com.routes.locationRoutes
import com.routes.sagaRoutes
import com.routes.userRoutes
import io.bkbn.kompendium.core.routes.swagger
import io.ktor.server.application.*
import io.ktor.server.http.content.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.util.*
import io.micrometer.prometheusmetrics.PrometheusMeterRegistry

fun Application.configureRouting() {
    routing {
	// Prometheus metrics endpoint
	get("/metrics") {
	    val registry = application.attributes[AttributeKey<PrometheusMeterRegistry>("prometheus.registry")]
	    call.respondText(registry.scrape())
	}

	// Swagger UI for OpenAPI documentation (auto-generated by Kompendium)
	swagger(pageTitle = "One Piece Timeline API")

	// Serve frontend files from static/dist
	staticResources("/", "static/dist")

	// API routes
	eventRoutes()
	characterRoutes()
	locationRoutes()
	arcRoutes()
	sagaRoutes()
	eraRoutes()
	userRoutes()
    }
}
